### PR TITLE
Switch to URI.create()

### PR DESCRIPTION
**Pull request by gregturn**
`URI.create()` wraps `new URI()` and converts a `UriSyntaxException` into an `IllegalArgumentException`.

### CODE REVIEW

**Comment by gregturn** [comment]
Looks like the examples can leverage `Link.toLink()` which is the same thing.

**Comment by odrotbohm** [comment]
I've recently introduced `Link.toUri()` for sort of that purpose. Do you think we can move to that instead?

**Comment by gregturn** [comment]
@odrotbohm Done!

**Comment by gregturn** [comment]
Thanks @schauder!

**Pull request closed without merging**
