### PR TITLE
Changed linkTo so that it can be invoked outside of a HttpRequest.

### PR DESCRIPTION
**Pull request by nickgrealy**
Changed linkTo so that it can be invoked outside of a HttpRequest -
issue #408.
Added a linkTo method, which takes an explicit UriComponentBuilder.

I have signed and agree to the terms of the Spring Individual Contributor
License Agreement.

### CODE REVIEW

**Comment by gregturn** [comment]
@nickgrealy This looks quite interesting. Do you think you could squash and rebase your PR against latest master?

**Comment by pivotal-issuemaster** [comment]
@nickgrealy Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=410)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=410) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by otrosien** [comment]
I like the idea of being able to use linkTo outside of the request context, but seriously, relying on catching an IllegalStateException to proceed with the program flow cannot be the solution to it...

**Comment by gregturn** [comment]
Resolved via #408.

**Pull request closed without merging**
