### PR TITLE
Update IANA relation types

### PR DESCRIPTION
**Pull request by rolandKulcsar**
Updated IANA relation types, see: https://www.iana.org/assignments/link-relations/link-relations.xhtml

### CODE REVIEW

**Comment by gregturn** [comment]
Thanks @rolandKulcsar! When I unravel a #575, I can hopefully process your contribution.

**Comment by pivotal-issuemaster** [comment]
@rolandKulcsar Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=580)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=580) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@rolandKulcsar Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=580)!

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/483f8479bd1021fb744ba49c11884086784ffe2e.

Thanks @rolandKulcsar!

**Pull request closed without merging**
