### PR TITLE
Added X-Forwarded-Path to ControllerLinkBuilder

### PR DESCRIPTION
**Pull request by nickgrealy**
I've added `Added X-Forwarded-Path` handling in the ControllerLinkBuilder, so that context paths can be handled.

I have signed and agree to the terms of the Spring Individual Contributor
License Agreement.

### CODE REVIEW

**Comment by gregturn** [comment]
I'm trying to find a spec for x-forwarded-path to check things out and I can't. Do you have link documenting proper behavior?

**Comment by nickgrealy** [comment]
@gregturn - no, unfortunately I don't have any supporting documentation. 

I came across it (generally), while looking for documentation on `X-Forwarded-Host` - which [I also couldn't find in w3c.org](https://www.google.com.au/search?q="x-forwarded-host"+site:w3c.org), yet exists in `ControllerLinkBuilder`.

Unless I'm mistaken, use of HTTP header prefix `X-` [is generally discouraged](http://tools.ietf.org/html/draft-saintandre-xdash-00).

Let me know what you want me to do with this...

**Comment by nickgrealy** [comment]
The issue number would probably help too... #143

**Comment by nickgrealy** [comment]
@gregturn - just wondering, who can action the backlog of push requests? There's a few that have been sitting around for a while now...

**Comment by olivergierke** [comment]
We can't just add some code for a header that's not specified anywhere.

**Comment by thebignet** [comment]
+1  Didn't see this PR before creating #431 .

**Comment by olivergierke** [comment]
As indicated above, nothing of this is going to make it unless we find a reliable source specifying the behavior of that header.

**Comment by thebignet** [comment]
Apparently, the [RFC](https://tools.ietf.org/html/rfc7239) has no mention for X-Forwarded-Host nor X-Forwarded-Port.

X-Forwarded-Path is a made up header with no specification, but there seems to be a concensus as to how it should be used in proxies (see [here](https://www.npmjs.com/package/linkto), [and here](http://lists.osgeo.org/pipermail/mapproxy/2013-April/001567.html) for examples).

Since it is a non invasive solution meaning that not using this header has no side effects, and that its definition is quite clear, it can be included in spring-hateoas.

**Comment by nickgrealy** [comment]
+1 for precedent... @olivergierke - https://github.com/spring-projects/spring-hateoas/commit/3f8b90e2b522f6d597804b3dcc43527c9a981f67

Is `X-Forwarded-Host` and `X-Forwarded-Port` part of a spec? and if not, should they be removed?

Thanks, Nick

**Comment by gregturn** [comment]
X-Forwarded-* appears governed by a draft spec here => http://tools.ietf.org/html/draft-ietf-appsawg-http-forwarded-10

Interestingly, I found RFC7239 here => http://tools.ietf.org/html/rfc7239, which appears designed to replace all the X-Forwarded headers.

If that's not enough fun, RFC6648 deprecates the "X-" prefix.

Not sure how to square non-standard, haphazard headers with a newly minted spec for the best approach on this project.

**Comment by nickgrealy** [comment]
Ok, well I'm happy with whatever you guys decide.

Just a thought, what if the `X-Forwarded-*` header handling was a togglable feature - defaulting to disabled - which people could enable (somehow)? Give the choice to the people!

**Comment by sebster** [comment]
I was wondering what the specification of this seems to be.

I've run into the same issue and really need a X-Forwarded-Path or equivalent header (to a reverse proxied rest service to avoid needing cross origin requests from a html5 client). RFC7239 seems to leave room for a Forwarded-Path header in section 5.5 (Extensions), specifically mentioning the reverse proxy situation.

The problem with ControllerLinkBuilder as it is now is that there is no way to alter or extend it's behavior: the constructor is package scoped, the getBuilder() as well as the linkTo methods are all static, and the "wiring" of the UriComponentsBuilder instance is fixed by the getBuilder() method implementation. The only option I see at the moment is to just copy the class and modify it and use the modified one instead; but it's not a very nice option.

**Comment by osvaldopina** [comment]
I developed a [framework](https://github.com/osvaldopina/linkbuilder) to render links in spring hateoas projects. In the current snapshot I'm working on clarifying the extension points. One of these extension points allows you to customize how url parts are obtained. 

There is a chain of reponsability in which each processing object can contribute with url parts (scheme, host, port and context path). 

[This integration test](https://github.com/osvaldopina/linkbuilder/blob/master/examples/src/test/java/com/github/osvaldopina/linkbuilder/example/extensions/requestpartsfactorylist/RequestPartsFactoryListTest.java) using [this configuration](https://github.com/osvaldopina/linkbuilder/blob/master/examples/src/main/java/com/github/osvaldopina/linkbuilder/example/extensions/requestpartsfactorylist/Application.java) shows how it can integrate your own processing object into the chain.

**Comment by otrosien** [comment]
Should be obsolete now. Current master is delegating this to UriComponentsBuilder, which is base-path aware. (use `X-Forwarded-Prefix` header. see also https://jira.spring.io/browse/SPR-12500)

**Comment by olivergierke** [comment]
Sure? This one is about `-Path` the ticket you linked to is about `-Prefix`.

**Comment by otrosien** [comment]
Well, that should be the header to set if you want to add a base-path to your URLs.

**Comment by michael-simons** [comment]
Funny, how I end up finding a ticket and personally knowing everyone involved.

The project right here is using `-Path` as well… While making the switch to "pure" Spring HATOAS without custom wrapper, we found generated URLs not working anymore. I suggested a starter containing a custom filter that maps Prefix to Path and I might just share that one.

**Comment by pivotal-issuemaster** [comment]
@nickgrealy Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=409)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=409) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by nickgrealy** [comment]
Fyi @olivergierke - I'm closing this PR due to inactivity. I can reopen again if requested.

**Pull request closed without merging**
