### PR TITLE
logref property should be optional

### PR DESCRIPTION
**Pull request by matteprl**
Originally mentioned in issue #478 - `logref` property in spring-hateoas project is required to have value, where in vnd.error specification this field is optional.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@matteprl Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1025)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1025) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@matteprl Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1025)!

**Comment by gregturn** [comment]
I agree the spec shows it to be optional and not required.

Are you able to update/add test cases that demonstrate `vnd.error` documents being rendered properly into JSON when `logref` is `null`?

**Comment by matteprl** [comment]
@gregturn Sure, will do.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/4f3be119c08a0b5db690fe6727632705baae8e4e.

**Comment by gregturn** [comment]
Feel free to take the snapshots out for a spin @matteprl

**Pull request closed without merging**
