### PR TITLE
Issue #361: Add Support for Resolving Property Values

### PR DESCRIPTION
**Pull request by jghiloni**
Add Support for Resolving Property Values in @RequestMapping(value)

Creates extra methods in `AnnotationMappingDiscoverer`, `ControllerLinkBuilder`, and `ControllerLinkBuilderFactory` to take an `Environment` object that can be used resolve placeholders. Accepts null `Environment`s to allow for backward compatibility.

### CODE REVIEW

**Comment by jhoeller** [comment]
Could use `PropertyResolver` instead of `Environment`, or even a plain `StringValueResolver` that could be adapted from a `PropertyResolver` (see `PropertySourcesPlaceholderConfigurer`'s implementation).

**Comment by jghiloni** [comment]
I like the idea, but I'm unclear as to where the `StringValueResolver` would get the values to use for substitution. Are you suggesting passing that in instead of an `Environment`, or somehow having the resolver as an instance variable?

**Comment by jhoeller** [comment]
Indeed, a `StringValueResolver` would have to be adapted from a `PropertyResolver` along the lines of `PropertySourcesPlaceholderConfigurer`, line 170+, so it's not really convenient to use for that purpose. Declaring `PropertyResolver` itself in such a signature might be the better choice, since `Environment` implements `PropertyResolver` and can therefore be passed in directly.

**Comment by jghiloni** [comment]
That's a good point. I'll make the necessary changes to reflect that (Passing `PropertyResolver` instead of `Environment`)

**Comment by jghiloni** [comment]
Any news on this?

**Comment by gregturn** [comment]
@jghiloni Ollie has been on PTO since SpringOne so things may be slow in coming out right now.

**Comment by jghiloni** [comment]
Ah, makes sense! No real rush, just noticed it was still open.

**Comment by olivergierke** [comment]
I don't like that now the `ControllerLinkBuilder` is now scattered with `PropertyResolver` parameters, something as it really breaks the abstraction (why would a client have to know about property resolution when calling those methods).

Maybe we can move the changes to the `ControllerLinkBuilderFactory`, which is an instance based alternative to the static `ControllerLinkBuilder`, which then can take an `Environment` as configuration setup to then use it during link resolution without polluting the parameter space?

**Comment by gregturn** [comment]
Catching up on @olivergierke 's comments on this feature. I'll try to see how this now operational PR can be retooled to not percolate this change into so many APIs.

**Comment by gregturn** [comment]
The related branch now shows a different solution that doesn't require altering any method signatures. It's also more composable.

**Pull request closed without merging**
