### PR TITLE
relax EmbeddedMapper to public access

### LINKED ISSUE #480: Jackson2HalModule.EmbeddedMapper private access dilutes reusability
https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/hal/Jackson2HalModule.java#L875

I am pursuing a custom Link Data shape (an intermediate in pursuit of json-api) different from HAL.

When attempting to reuse portions of Jackson2HalModule, I can't instantiate HalLinkListSerializer (public) without EmbeddedMapper unless I use the provided HalHandlerInstantiator which brings in its own custom ResourcesSerializer.

Making EmbeddedMapper class public resolves this issue.

### PR DESCRIPTION
**Pull request by karlthepagan**
Resolves #480

### CODE REVIEW

**Comment by Berastau** [comment]
+1

**Comment by gregturn** [comment]
I don't this is the solution we should pursue. Making such an internal class public is the wrong move. It should be elevated to its own full class, not an inner class. But given it's used to support HAL, I don't see the value in making this reusable. I wrote Collection+JSON support (#482) and needed no such class.

**Comment by pivotal-issuemaster** [comment]
@karlthepagan Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=481) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gregturn** [comment]
Closing due to lack of discussion.

**Pull request closed without merging**
