### PR TITLE
Make JacksonSerializationTest platform independent

### LINKED ISSUE #385: JacksonSerializationTest not platform independent
Running the tests of sprint-hateoas:master on Microsoft Windows results in a failure to  org.springframework.hateoas.alps.JacksonSerializationTest
due to the platform dependent line separator choice in line 90:

``` java
writesSampleDocument(org.springframework.hateoas.alps.JacksonSerializationTest)  Time elapsed: 0.18 sec  <<< FAILURE!
java.lang.AssertionError:
Expected: is "{\n  \"version\" : \"1.0\",\n  \"doc\" : {\n    \"href\" : \"http://example.org/samples/full/doc.html\"\n  },\n  \"descriptors\" : [ {\n    \"id\": \"search\",\n    \"doc\" : {\n      \"value\" : \"A search form with two inputs.\",\n      \"format\" : \"TEXT\"\n    },\n    \"type\" : \"SAFE\",\n    \"descriptors\" : [ {\n      \"href\" : \"#resultType\"\n    }, {\n      \"id\" : \"value\",\n      \"name\" : \"search\",\n      \"type\" : \"SEMANTIC\"\n    } ]\n }, {\n    \"id\" : \"resultType\",\n    \"doc\" : {\n      \"value\" : \"results format\"\n    },\n    \"type\" : \"SEMANTIC\",\n    \"ext\" : {\n      \"href\" : \"http://alps.io/ext/range\",\n      \"value\" : \"summary,detail\"\n    }\n  } ]\n}"
     but: was "{\r\n  \"version\" : \"1.0\",\r\n  \"doc\" : {\r\n    \"href\" : \"http://example.org/samples/full/doc.html\"\r\n  },\r\n  \"descriptors\" : [ {\r\n    \"id\" : \"search\",\r\n    \"doc\" : {\r\n      \"value\" : \"A search form with two inputs.\",\r\n      \"format\" : \"TEXT\"\r\n    },\r\n    \"type\": \"SAFE\",\r\n    \"descriptors\" : [ {\r\n      \"href\" : \"#resultType\"\r\n    }, {\r\n      \"id\" : \"value\",\r\n      \"name\" : \"search\",\r\n     \"type\" : \"SEMANTIC\"\r\n    } ]\r\n  }, {\r\n    \"id\" : \"resultType\",\r\n    \"doc\" : {\r\n      \"value\" : \"results format\"\r\n    },\r\n    \"type\" : \"SEMANTIC\",\r\n    \"ext\" : {\r\n      \"href\" : \"http://alps.io/ext/range\",\r\n      \"value\" : \"summary,detail\"\r\n    }\r\n  } ]\r\n}"
        at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
        at org.junit.Assert.assertThat(Assert.java:956)
        at org.junit.Assert.assertThat(Assert.java:923)
        at org.springframework.hateoas.alps.JacksonSerializationTest.writesSampleDocument(JacksonSerializationTest.java:73)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
```

Here is a patch:

``` patch
--- src/test/java/org/springframework/hateoas/alps/JacksonSerializationTest.java.orig   2015-09-05 22:04:19.883611900 +0200
+++ src/test/java/org/springframework/hateoas/alps/JacksonSerializationTest.java        2015-09-05 22:05:28.308525600 +0200
@@ -87,7 +87,7 @@
                                builder.append(scanner.nextLine());

                                if (scanner.hasNextLine()) {
-                                       builder.append("\n");
+                                       builder.append(System.getProperty("line.separator"));
                                }
                        }
```

### PR DESCRIPTION
**Pull request by rolandKulcsar**
Fix #385.

### CODE REVIEW

**Comment by gregturn** [comment]
@rolandKulcsar Looks cool, but why not use `System.getProperty("line.separator")`?

**Comment by rolandKulcsar** [comment]
@gregturn You are right, much cleaner, I fixed it. Thank you!

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/6d86feb120360c828db99f40d5628c1ce5be47cf

**Comment by gregturn** [comment]
Thanks @rolandKulcsar!

**Pull request closed without merging**
