### PR TITLE
Documentation: Fix typos, document links, and grammatical errors

### PR DESCRIPTION
**Pull request by rolandkrueger**
I found two unfinished sentences which I could not complete. I marked them with an ellipsis (...) so that they stand out a bit more. They still need to be completed by a maintainer:

* mediatypes.adoc: "Extract the properties from the `EntityModel` and turn them into ..."
* server.adoc: "Just as you can create links by pointing to Spring MVC controller methods (see <<server.link-builder.webmvc>> for details) you ..."

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rolandkrueger Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1190)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1190) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by rolandkrueger** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@rolandkrueger This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by odrotbohm** [comment]
Highly appreciated, Roland. I'll have a look tomorrow morning.

**Comment by rolandkrueger** [comment]
Thanks, you're welcome!

**Comment by odrotbohm** [comment]
That's merged and back-ported. Thanks again for that thorough review!

**Pull request closed without merging**
