### PR TITLE
Fix package name 'vnderror' to 'vnderrors' in migration script

### PR DESCRIPTION
**Pull request by yanwenkun**
- Before:
Will have package named: `hateoas.mediatype.vnderror`
- After
Will have package named: `hateoas.mediatype.vnderrors`

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@yanwenkun Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1133)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1133) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@yanwenkun Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1133)!

**Comment by gregturn** [comment]
Instead of tweaking a very HAL oriented error handler that has seen no action for years, I’m in favor of this => https://github.com/spring-projects/spring-hateoas/pull/1057

WDYT @odrotbohm?

**Comment by odrotbohm** [comment]
The suggested change is purely about the migration script.

**Comment by odrotbohm** [comment]
That's merged and backported.

**Pull request closed without merging**
