### PR TITLE
Improve performance of linkTo(Object) in ControllerLinkBuilderFactory with caching

### PR DESCRIPTION
**Pull request by rolandKulcsar**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@rolandKulcsar Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=578)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=578) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gregturn** [comment]
This looks great!

When I finish up working on the Affordances API, I should be able to take a closer look.

**Comment by gregturn** [comment]
@rolandKulcsar Reason you closed this PR?

**Comment by rolandKulcsar** [comment]
@gregturn This solution has negligible performance advantage.

**Pull request closed without merging**
