### PR TITLE
Add method support to JaxRsLinkBuilder.

### PR DESCRIPTION
**Pull request by Vulcannis**
Pulled out some common code from ControllerLinkBuilderFactory into LinkBuilderSupport, and added necessary methods to JaxRsLinkBuilder + Factory to support linking to controller/service methods.

Looking over the commit it's a tad big, would it be preferable if I submit the unsquashed commits?

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Vulcannis Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=207)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=207) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by gregturn** [comment]
@Vulcannis Indeed, if you could squash this PR and rebase against master, we can examine your proposal better.

**Comment by gregturn** [comment]
I'm afraid this contribution is not currently acceptable. It violates several package boundaries. For example, moving several support classes from `org.springframework.hateoas.mvc` up to the top level, yet continue to use `ControllerLinkBuilder`, and Spring MVC-based class, won't work. Also, updating code in `org.springframework.hateoas.core` and having it leverage stuff in the adjacent `mvc` subpackage is also unacceptable.

**Comment by gregturn** [comment]
Best approach might be to start clean and try to reimplement, given I also spotted mods that I also see already in the master branch. Also saw a refactoring of "required" that didn't seem to fit the scope of this proposoal.

**Pull request closed without merging**
