### PR TITLE
#402 - Support fo JSON API media type

### PR DESCRIPTION
**Pull request by atkawa7**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@atkawa7 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=969)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=969) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@atkawa7 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=969)!

**Comment by gregturn** [comment]
Any tests?

**Comment by atkawa7** [comment]
@gregturn Not yet :). But I will. Did you see my question regarding `Identifiable`. I wanted to find out that before I could write any tests

**Comment by gregturn** [comment]
Yes. I’ll let @oliverdrotbohm address that.

**Comment by toedter** [comment]
great to see this!

**Comment by atkawa7** [comment]
@odrotbohm Thanks I will add the requested changes

**Comment by atkawa7** [comment]
@odrotbohm @gregturn 

After implementing IdentityExtractor SPI. I realized there are couple of issues.
Suppose we had a model User 

```java
@Data
class User{
    private String id;
    private String firstName;
    private String lastName;
} 
```


then we expect the resulting json api  for the endpoint `/users/1` to be 

```json
{
    "data" :{
        "id": "1",
        "type: "users",
        "attributes": {
            "firstName": "john",
            "lastName": "doe"
        }
    }
}
```


However if we introduce an `IdentityExtractor` SPI. Then we would have something like 

```java
public interface IdentityExtractor {
    default String getId(Object entity){
        return null;
    }
    default String getType(Object object){
        return null;
    }
}

public interface IdentityExtractorProvider {
    IdentityExtractor identityExtractor();
}

public class DefaultIdentityExtractorProvider implements IdentityExtractorProvider {
    @Override
    public IdentityExtractor identityExtractor() {
        return new IdentityExtractor() {
        };
    }
}
```

In this case its difficult to dynamically ignore the (type, id) fields then we will end up with 

```json
{
    "data" :{
        "id": "1",
        "type: "users",
        "attributes": {
            "firstName": "john",
            "lastName": "doe",
            "type": "user",
            "id": "1"
        }
    }
}
```

However if we let the user extends  `Identifiable` which already has ignore annotations then we won't have that issue

```java
public interface Identifiable {
    @JsonIgnore
    String getId();

    @JsonIgnore
    String getType();
}
```

Is there any way to dynamically remove (id, type) from objects. I do not want to add another `toAttributes` method in the `IdentityExtractor` interface

**Comment by atkawa7** [comment]
@odrotbohm @gregturn PING

**Comment by gregturn** [comment]
When I use Jackson, it's an experiment everytime, despite using it all the time.

Several options for shaping the outputs can be found here => https://www.baeldung.com/jackson-ignore-properties-on-serialization

Think about what things can be put inside the serializer/deserializer code that would JSON API specific and hence not have to leak outside that.

**Comment by niltz** [comment]
@atkawa7 any progress on this? I would be interested in helping out. Is this the most up to date code, or do you have work not yet pushed to your fork?

**Comment by sodastreamssolutions** [comment]
Do you have any rough plan on when more or less to merge this ?

**Comment by odrotbohm** [comment]
It definitely won't be in 1.0. There is a mechanism to add media type implementation from the outside though, so if you really fancy to give it a try, the code should be able to be packaged in a separate JAR and be consumed by Spring HATEOAS. It would also be very helpful to know in case you run into issues in that exercise.

**Comment by magneticflux-** [comment]
@atkawa7 What's the status of this PR? I'm packaging it as a jar for private use and testing, but I could publish it as a repo and on Bintray and give you access if you wanted.

I assume you expect these changes to eventually be under Apache License 2.0 (the license for this repo), but you still retain copyright after signing the CLA so I don't want to redistribute your code without your approval.

**Comment by magneticflux-** [comment]
@odrotbohm I'm having trouble adapting it from the outside because `HypermediaType` is an enum instead of something like `MediaType`. Specifically, I'm trying to use `@EnableHypermediaSupport` so I can use Spring Data Rest. It also just seems like Spring Data Rest is tightly coupled to `HAL` currently.

**Comment by gregturn** [comment]
Per #1055, you don't actually need `@EnableHypermediaSupport` in order to register custom media types. If registered as a Spring bean in the application context, custom media types should be picked up and hence configured to generate proper hypermedia respones to MVC/WebFlux requests.

@odrotbohm and I spotted that ALL the annotation above does is translate `HypermediaTypes` -> `MediaType`, and then use that to filter against the built in media types before registering them. ANY media type simply registered directly into the application context will be applied.

**Comment by gregturn** [comment]
I believe the major hold up on this PR was the lack of test cases.

**Comment by MojoJojo** [comment]
Hi,

Any updates on this PR?

**Comment by aadityamaheshwari** [comment]
Do we have any updates on this? or even on the progress?

**Comment by jameshwh** [comment]
It looks the implementation doesn't support "relationships" (correct me if i am wrong), anyway I downloaded these source files and finally get it work to output JSON:API response. The way I wrapper the response is as below in case someone want do the same as me (or feel free to let me know if there's a better way to do so), 
```java
    @RequestMapping(value = "/mobiles",
            produces = { "application/vnd.api+json", "application/json" },
            method = RequestMethod.GET)
    public CollectionModel<EntityModel<Mobile>> getMobiles(Integer page, Integer size, String nameLike, String hardwareIdLike, String vinLike, Boolean withAssignedDriver, Integer fleetId) {
        try {
            List<Mobile> mobileList = buildMobileList();
            List<EntityModelMixin> mixins = new ArrayList<>();
            for (Mobile mobile : mobileList) {
                Link selfLink = linkTo(methodOn(MobilesApiController.class).getMobileById(""+mobile.getMobileId())).withSelfRel();
                EntityModelMixin mixin = new EntityModelMixin<>(mobile, selfLink);
                mixins.add(mixin);
            }
            Link selfLink = linkTo(methodOn(MobilesApiController.class).getMobiles(page, size, nameLike, hardwareIdLike, vinLike, withAssignedDriver, fleetId)).withSelfRel();
            return (CollectionModel) new CollectionModelMixin(mixins, selfLink);
        } catch (Exception e) {
            log.error("Couldn't serialize response for content type application/vnd.api+json", e);
            // Error to be handled somewhere
        }

        return null;
    }
```



Please remember to create a file spring.factories under the src/main/resources which is required by Spring, and put the content below in it:
```
org.springframework.hateoas.config.MediaTypeConfigurationProvider=\
 org.springframework.hateoas.mediatype.jsonapi.JsonApiMediaTypeConfigurationProvider
```
This will register the JSON API provider and be loaded accordingly.

**Comment by gregturn** [comment]
See also: https://github.com/toedter/spring-hateoas-jsonapi

**Comment by gregturn** [comment]
Superceded by https://github.com/toedter/spring-hateoas-jsonapi and #1337.

**Comment by gregturn** [comment]
It's probably easier to let the community manage this type.

If you check in, they are probably open to contributions!

**Pull request closed without merging**
