### PR TITLE
Upgrade to spring 4.1.0.RELEASE

### PR DESCRIPTION
**Pull request by dilipkrish**
Not really sure if there is a reason this project is lagging behind the release train. Seemed simple enough to upgrade.

### CODE REVIEW

**Comment by olivergierke** [comment]
Superseded by #311, upgraded to Spring 4.0.9.RELEASE.

**Comment by dilipkrish** [comment]
Why 4.0.9 vs 4.1.x?

**Comment by olivergierke** [comment]
The policy (mostly originating from Spring Data modules) is to be on the last but one major version. A reasonable balance to not cut off users that might not be able to upgrade to the latest and greatest (due to whatever reason) but still stay relatively up to date.

Note, that the version is only a lower baseline for us to build against. We make sure, Spring HATEOAS is  working fine on more recent versions of Spring Framework.

**Comment by dilipkrish** [comment]
:+1: Thanks!

**Pull request closed without merging**
