### PR TITLE
Faster implementation of link generation

### PR DESCRIPTION
**Pull request by mst-avaleo**
I'm posting an alternative implementation for link generation which is 2x faster than the newest 0.25.x version. In the benchmark posted in #977 it gets around 7-9s.

The alternative implementation is based on the idea that link generation should be a highly cacheable operation. Links are usually referring to limited number of controller methods / resources, so there should be possibility to create some set of templates which will be just filled with parameters which are coming from the request or context. Building template should be done once, and it should contain most of the costly operations (like processing of annotations etc). Later filling the template with request parameters should be as simple as possible.

Unfortunately I haven't found a way to implement that by extending current process. The proposed change is a implementation on side, which is using building blocks from the library. 

Here's example of the usage:
```
import static org.springframework.hateoas.mvc.ControllerLinkBuilder.methodOn;
import static org.springframework.hateoas.mvc.FastLinks.linkTo;

String href = FastLinks.linkTo(methodOn(SampleController.class).sampleMethod(1L));
```

The PR is against 0.25.x since version 1.0.0 is a lot of slower (see #977).

We are using this fork for more than year in several services on production systems.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mst-avaleo Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=978)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=978) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by odrotbohm** [comment]
Can you elaborate on where you think the performance wins are coming from mostly. I see a lot of encoding code and wonder if we wouldn't be better off fixing that in Spring Framework itself. URI encoding is a science in itself and I am not really eager to start maintaining that kind of code if there's a well maintained alternative in the Framework. If that is slow, we should fix that.

The lack of Javadoc is problematic as well.

You argue that the templates are highly cacheable, which makes me wonder whether we could actually get away with more dedicated caching in various places.

**Comment by odrotbohm** [comment]
After playing with the benchmark and the profiler today I had a few ideas I thought I’d summarize here as they seem related to the proposal. The current `LinkBuilder` implementations are based on `UriComponents` to a large degree. That means the call to `linkTo(…)` immediately creates an expanded URI containing the values handed into the dummy method invocations. This approach allows us to create the `UriComponents` in one pass, which seems effective.

However, that mix up between static information (essentially a URI template backing the method) and dynamic information (the parameter values used during the dummy method invocation). That prevents us from caching the static part. If we built up that in a first pass, we could remember that based on the sole static method information and for subsequent invocations of the same method, we could reuse that template and simply expand it with different values.

It felt like your implementation was sort of heading into the same direction. I just think we shouldn’t have the need to implement as many fundamental building blocks ourselves. Would you be interested in trying to implement this two-pass algorithm based on the existing abstractions (`UriTemplate` et al.)?

**Comment by mst-avaleo** [comment]
Implementing two-pass algorithm using existing abstractions will be more difficult than doing it on side which took several man days (BTW I full agree with all its cons you pointed out like reimplementation of fundamental building blocks). Plus: the latest implementation on 0.25.x branch has similar the performance to the impl in the PR (and to our internal fork).  In result I'll rather not get enough time needed for such two-pass algorithm when expected improvement will not be significant. 

Anyway I'm very happy that my PRs started a discussion regarding performance and triggered several improvements in the library :-)

**Pull request closed without merging**
