### PR TITLE
Support for HATEOAS-Links in Json-Views

### PR DESCRIPTION
**Pull request by tinne**
The @JsonView annotation supports filtering class trees in order to provide custom views on specific partial data, cf. eg. https://spring.io/blog/2014/12/02/latest-jackson-integration-improvements-in-spring

The main purpose of this patch is to provide a means of views including the links properties of REST models using ResourceSupport. Usage: extend Link.LinkView to denote your view properties.

Also contributes bundlor support for eclipse m2e environment: tell eclipse to run bundlor:bundlor even on incremental builds.

### CODE REVIEW

**Comment by gBarrerasSanz** [comment]
Hi,
I'm interested in including this feature in my gradle project. For now, the latest version I could get is http://mvnrepository.com/artifact/org.springframework.hateoas/spring-hateoas/0.17.0.RELEASE. How could add this github project to my gradle script? 
Thank you!

**Comment by gregturn** [comment]
Use 0.18.0.Build-snapshot from repo.spring.io/lib-snapshot.

**Comment by gBarrerasSanz** [comment]
Sorry for the inconvenience, but I've just tried the build from http://repo.gradle.org/gradle/repo/org/springframework/hateoas/spring-hateoas/0.18.0.BUILD-SNAPSHOT/ and it does not contain nor ResourcesLinksVisible or Link.LinkView class interfaces. As far as I could understand, my View classes must extend one of those interfaces (don't know which of them exactly though). 
Thank you!

**Comment by tinne** [comment]
@gBarrerasSanz This pull request has not yet been merged into the main project, please build from source by cloning https://github.com/tinne/spring-hateoas.git in the meantime.

**Comment by gBarrerasSanz** [comment]
@gregturn @tinne Thank you guys for your attention. I did make it work.

**Comment by sergiorc** [comment]
Hi all
Does anybody know when this pull request is going to be merged?
Thanks a lot

**Comment by olivergierke** [comment]
Any chance you add a few test cases to express the purpose of the changes and prevent regressions? Also, please remove all changes not related to this ticket, i.e. the cahnge in `pom.xml` and the removal of the warning suppression.

**Comment by tinne** [comment]
I did not post my test project and an still digging through your test code, so you will get your tests some day later.

Extracting removal of the warning expression was most easy so you got this as a separate pull request first.

Let me first start with the semantics (notation borrowed from jasmine):

* describe("test set", {
  * describe("Resource View Tests", {
    * it("ignores links when rendering them to JSON, as before", assertEquals(objectMapper.writeValueAsString(someBean), objectMapper.writeValueAsString(createResourceWithLinks(someBean)))),
    * it("writes out links when rendered to JSON on annotating with @JSonView(ResourceLinkView.class)",
assertEquals(objectMapper.writeValueAsString(subclassAndAddLinksByHand(someBean),
objectMapper.writeValueAsString(createResourceWithLinks(someBean)))),
    * it("writes out links when rendered to JSON and filters bean itself",
assertEquals(objectMapper.writeValueAsString(subclassAndAddLinksByHand(otherBeanWithJsonViewPropertiesAnnotatedWithInterfaceExtendingResouceWithLinks), objectMapper.writeValueAsString(createResourceWithLinks((otherBeanWithJsonViewPropertiesAnnotatedWithInterfaceExtendingResouceWithLinks))))  },
  * describe("Resources View Tests", { /** same for collections **/ },
  * describe("Resource(s)Support View Tests, { /** dito **/ }}}}

**Comment by DharaSingh** [comment]
Hi olivergierke,
I am using 0.19.0.RELEASE for hateoas but still did not find any view which can help me to include links into my model object. 

And in general most of the models have id and method implemented getId(), and ResourceSupport has method getId to get link. is there any other way to use it except changing the method name in model class ?

**Comment by ianaz** [comment]
Same issues as @DharaSingh

**Comment by tinne** [comment]
Thank you for the discussion. Kindly move it (and your support) to #387.

**Comment by ajitkumargiri** [comment]
Thanks @tinne and @odrotbohm ,
 I am using The @JSONVIEW annotation for filtering the response. But It is blocking RepresentationModel _link json attribute.
I am using Spring HateOAS 1.0.1.RELEASE and Spring boot 2.2.1.RELEASE .
Any help how to implement @Jsonview in hateoas RepresentationModel . 
Is current spring boot support hateoas with @jsonview.

**Pull request closed without merging**
