### PR TITLE
[ISSUE#743][Manish]Updated Hop and Traverse class to use specific hops

### PR DESCRIPTION
**Pull request by manishpmisra**

### CODE REVIEW

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/b60799d7fa6072282744170293b7f9f4fa793a4f and https://github.com/spring-projects/spring-hateoas/commit/df618efd12006efe0c9ca17413a64b8f0a5b33f1.

**Comment by gregturn** [comment]
Thanks @manishpmisra!

**Comment by manishpmisra** [comment]
@gregturn @odrotbohm Quick question: why I don't see my name as a contributor in list. I can see you have added my name under authors, but it is not displaying in Contributor list. 

Thanks in advance.

**Comment by gregturn** [comment]
The commit with your name doesn’t appear to link to a GitHub id. Did you change your account at some point between when you coded and now?

**Comment by manishpmisra** [comment]
Nope, no change and I have always used the same. At some places I can see
the linked one and unlinked one both.

**Comment by manishpmisra** [comment]
Look at 
https://github.com/spring-projects/spring-hateoas/pull/747/commits/884a3b071628fcdeff198a198c7a3dc76b00de86

and 

https://github.com/spring-projects/spring-hateoas/pull/747/commits/cec563b07bad5d84bb53ed276170e5668756e3f9

one has linked user another one does not.

**Comment by gregturn** [comment]
@manishpmisra That commit appears associated with an email address connected to paloaltonetworks.com (don't want to list it here).

If you add that email address to your github profile, it should link that commit to your github id.

**Comment by manishpmisra** [comment]
okay thanks, i will try that.

**Comment by manishpmisra** [comment]
that worked, but still it is not showing under contributor list, look at:
https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/client/Traverson.java
https://github.com/spring-projects/spring-hateoas/blob/master/src/main/java/org/springframework/hateoas/client/Hop.java

**Comment by gregturn** [comment]
I’m sure it will eventually get consistent. I don’t know if it takes time or if the metric will be recompiled when the next commit is pushed to master.

**Comment by gregturn** [comment]
Yup, I can see @manishpmisra now listed on the contributors section.

**Pull request closed without merging**
