### PR TITLE
issue #288 Allow links on particular rels to be displayed as an array even if there is only one link

### PR DESCRIPTION
**Pull request by vivin**
This change allows links behind certain rels to always be wrapped by an array regardless of cardinality.

This is related to #291. Instead of trying to control the wrapping based on a resource-rel combination, this approach controls the representation of the link simply based on the rel. Hence, if the specified rels appear in _any_ resource, they will always be wrapped inside an array regardless of cardinality. 

I think this allows for the development of more-consistent representations. If there is ever more than one link behind a particular rel (under any resource), I think it makes more sense to maintain that consistency across all resources by ensuring that the links under that rel are always wrapped in an array.

### CODE REVIEW

**Comment by vivin** [comment]
@olivergierke Please let me know if this approach makes more sense. Thanks!

**Comment by vivin** [comment]
@olivergierke Have you had a chance to look at this?

**Comment by vivin** [comment]
@olivergierke I'd appreciate some feedback on this when you get a chance. It's a feature that I'd like to get in (with whatever changes you think are necessary) because it's having an impact on an API that I'm currently building.

**Comment by vivin** [comment]
@olivergierke It's been a little over a month since I opened this pull request. I'd appreciate any sort of feedback on this. I understand that you might be busy and that you might not have a chance to attend to this, but even a comment saying so would be appreciated. Thanks.

**Comment by vivin** [comment]
@olivergierke I've updated this PR and renamed the class to `HalCollectionRels`.

**Comment by chasecaleb** [comment]
@olivergierke I'm not sure if you aren't interested in this PR or you haven't had time to approve it, but I'm using this project at work and it would be a big help in simplifying client code.

**Comment by edrik** [comment]
+1

**Comment by ch4mpy** [comment]
+1

**Comment by pivotal-issuemaster** [comment]
@vivin Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=295)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=295) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@vivin Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=295)!

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/7cd1fb8f91b3c38071d062fe7f98b3bbe31f54d0.

**Pull request closed without merging**
