### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by rolandKulcsar**
Some typo fixes.

### CODE REVIEW

**Comment by gregturn** [comment]
Looks great @rolandKulcsar. If you would squash and rebase against master, I can push this on through.

**Comment by rolandKulcsar** [comment]
Sure, I think it has succeeded.

**Comment by gregturn** [comment]
@rolandKulcsar it all passes. If you can rebase against master, and squash it all into one commit, that would be handy.

**Comment by rolandKulcsar** [comment]
@gregturn I think it should be OK now.

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/82fb6ef9d2ce97205da6b5b63eb10704546c3aa1.

Thanks @rolandKulcsar!

**Pull request closed without merging**
