### PR TITLE
#1098 - Institute checks for client-only setups.

### PR DESCRIPTION
**Pull request by gregturn**

### CODE REVIEW

**Comment by odrotbohm** [comment]
I like where the configuration implementation changes go but am pretty sure we should find a different way to expose that in the configuration. As you already described in the ticket, the client/server distinction does not map very well to the `WebStack` enum.

I wonder if we can hide the the distinction between simple classpath checks rather. If both the server and client related configuration are available as separate configuration classes, we could still guard their inclusion by classpath checks for e.g. `DispatcherServlet` or a simple test for `RestTemplate`'s presence.

I know that technically, `RestTemplate` is not part of MVC (so that activating support for it is a bit weird) but the original split we were trying to establish with the enum was servlet/blocking VS. reactive/non-blocking. Maybe we can introduce new enum values that better reflect this distinction in a separate ticket and deprecate the current ones. However, the need to explicitly use these flags should be an exception, not the rule.

**Comment by gregturn** [comment]
@odrotbohm I've made the suggested changes. This led me to push the logic of what config files to offer into the enum as well, simplifying `WebStackImportSelector`.

My remaining question is: do we still need a public API for `isClientAvailable` and `isServerAvailable`, or can we simply keep those as private, internal variables that feed `getAvailableConfigurations()`?

On one hand, I'd say reduce the API footprint. On the other, it may be handy to know the details of your current situation.

**Comment by odrotbohm** [comment]
Looks good to me! I think we can get rid of the accessors for the `boolean` flags.

**Comment by gregturn** [comment]
Resolved via cf0c606e.

**Pull request closed without merging**
