### PR TITLE
Fixed some grammatical and spelling errors

### PR DESCRIPTION
**Pull request by martinotten**

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@martinotten Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1097)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1097) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@martinotten Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=1097)!

**Comment by gregturn** [comment]
Resolved via https://github.com/spring-projects/spring-hateoas/commit/8c6dfc922c648e5b3e5df2fc193a78336b47e01b.

**Comment by gregturn** [comment]
Thanks @martinotten!

**Comment by gregturn** [comment]
Backported to 1.0.x via 552adbd0.

**Pull request closed without merging**
