### PR TITLE
Add support for @JsonProperty annotation for DefaultMetadataProperty field "name".

### PR DESCRIPTION
**Pull request by talentedasian**
Make the default name of the DefaultMetadataProperty field "name" as the value of a @JsonProperty annotation given that the value is present, else, use the default implementation. 
Tests are located in the HalFormsTemplateBuilderUnitTest.

### CODE REVIEW

**Comment by talentedasian** [comment]
Fixes #1563

**Comment by talentedasian** [comment]
Closes #1563

**Comment by odrotbohm** [comment]
@talentedasian – I have to ask you again. Please stop opening and closing tickets at will. We're organizing our work around this and having to follow up on all the notifications we get from ticket actions that appear for no obvious reason is time consuming. Please, just don't. Thanks!

**Comment by odrotbohm** [comment]
I ended up choosing a slightly different approach to fixing that bug. Thanks for the contribution nonetheless.

**Pull request closed without merging**
