### PR TITLE
Update spring-doc-resources and highlight

### PR DESCRIPTION
**Pull request by Buzzardo**
Update spring-doc-resources to get the latest look and feel and nicer
code listings.

### CODE REVIEW

**Comment by odrotbohm** [comment]
One reason we haven't upgraded yet is this ticket: https://github.com/spring-io/spring-doc-resources/issues/30.

**Comment by Buzzardo** [comment]
OK. I assigned Damien to that issue. I'm sure he can fix it quickly.

**Comment by gregturn** [comment]
Resolved via e4fc1053.

Thanks @Buzzardo!

**Comment by odrotbohm** [comment]
Has that fixed version of Docs resources already been released?

**Comment by Buzzardo** [comment]
No, it hasn't. Damien fixed the issue five days ago, but the latest release was 18 days ago. It'll have to go in the 0.2.1 release. I don't know when that release will be made. @bclozel might know.

**Comment by bclozel** [comment]
I’ve just published 0.2.1.RELEASE with those fixes and other changes.

**Comment by odrotbohm** [comment]
Didn't want to rush anyone. Thanks for the quick turnaround!

**Pull request closed without merging**
