### PR TITLE
Added ControllerActionBuilder with actionFor method.

### PR DESCRIPTION
**Pull request by dschulten**
Improved support for requests which require that the client sends data to the server. The goal is not to rely on out-of-band information for this.

The new ActionDescriptor allows to create responses which tell the client how to send data to a resource, e.g. how to build POST and PUT bodies or which GET parameters to use in a query.

See the javadoc of ControllerActionBuilder and HtmlResourceMessageConverter for usage and SamplePersonController and HtmlResourceMessageConverterTest-context.xml for an example.
Currently using spring-test-mvc with WebContextLoader to stay compatible with Spring 3.1.x

### CODE REVIEW

**Comment by aheusingfeld** [comment]
@olivergierke could you please review this. The "method" support would be very much appreciated. Thanks. ;)

**Comment by olivergierke** [comment]
To be honest, the more I look into it, the less I am convinced that merging this is a good idea:

- we're basically stuck with something quite involved but still very rudimentary. Only `@RequestParam` is currently supported, no `@PathVariable`, no `@ModelAttribute`.
- `ControllerActionBuilder` seems to be repeating a lot of code that already exists in the infrastructure and probably only works in the exact use case it was written for (what about proxied requests etc.)

In general, my biggest concern is that this is far from done and basically lacking a description of the general approach, its limitations. We currently don't have neither a form nor HTML strategy with Spring HATEOAS and I think that we need to come up with a more exhaustive concept to it before going forward with it. Open for suggestions.

**Comment by dschulten** [comment]
Since I am the author of that pull request: After the pull request never
made it into spring-hateoas, I have created a LinkBuilder implementation 
called AffordanceBuilder [1]
which works as a drop-in replacement for ControllerLinkBuilder. It creates 
an Affordance, which is a hateoas Link with additional traits (httpMethod, 
RequestParam, RequestBody, multiple methods per rel). It also supports all 
features of the RFC5988 Link header.

@olivergierke if you are interested I would be happy to create another pull 
request which adds AffordanceBuilder back into spring-hateoas. I'll be at 
JAX, maybe we can meet there.
After all, hydra-java stands firmly on the shoulders of spring-hateoas :)
Conceptually, AffordanceBuilder would be a better choice than this pull 
request.

The goal of hydra-java is to support hypermedia types with "forms" support, 
first hydra, but xhtml and uber converters are coming soon.

[1] 
https://github.com/dschulten/hydra-java/blob/master/README.asciidoc#affordancebuilder-for-rich-hyperlinks-from-v-020
[2] https://github.com/dschulten/hydra-java/tree/master/spring-hateoas-ext

Am 09.03.2015 um 01:44 schrieb Alexander Heusingfeld:

**Comment by olivergierke** [comment]
That's great news, Dietrich. As JAX is not too far away anymore. Shall we get together there and find some time to discuss things? Wouldn't mind @aheusingfeld joining us as he seems to be buys in that area, too.

**Comment by aheusingfeld** [comment]
> I have created a LinkBuilder implementation called AffordanceBuilder [1] which works as a drop-in replacement for ControllerLinkBuilder. It creates an Affordance, which is a hateoas Link with additional traits (httpMethod, RequestParam, RequestBody, multiple methods per rel).

Great! That's almost exactly what I started with yesterday! Will look at your implementation instead. \o/

> Wouldn't mind @aheusingfeld joining us as he seems to be buys in that area, too.

Yes. I'll be there Apr 21 - 23. Looking forward to see you there.

**Comment by dschulten** [comment]
My talk is on the 23rd at 17:00-18:00, so best after that or right after 
Alexander's talk.

Dietrich

**Comment by gregturn** [comment]
Superceded by #612 and resolved via https://github.com/spring-projects/spring-hateoas/commit/70448a854098343897fd99e3227b4a61db54b921.

Final solution isn't precisely the same thing, but we plan to iterate over it in the near future and expand to support other mediatypes. Feel free to check the HAL-FORMS section of code and their corresponding unit tests.

Also, see monitor [Spring HATEOAS Examples repo](https://github.com/spring-projects/spring-hateoas-examples) as we plan to add an Affordances example very soon.

**Comment by pivotal-issuemaster** [comment]
@dschulten Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=71)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=71) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@dschulten Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=71)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-projects/spring-hateoas&pullRequestId=71) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Pull request closed without merging**
